# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# =============================================================================
# ⚠️  AUTO-GENERATED FILE - DO NOT EDIT  ⚠️
# Generated by: ./tools/generate_plugin_artifacts.py
# =============================================================================
# fmt: off
"""Plugin Type Enums - generated dynamically from the plugin registry."""

from typing import TYPE_CHECKING, TypeAlias

from aiperf.plugin import plugins
from aiperf.plugin.extensible_enums import create_enum

__all__ = ["APIRouterType", "APIRouterTypeStr", "AccuracyBenchmarkType", "AccuracyBenchmarkTypeStr", "AccuracyGraderType", "AccuracyGraderTypeStr", "ArrivalPattern", "ArrivalPatternStr", "CommClientType", "CommClientTypeStr", "CommunicationBackend", "CommunicationBackendStr", "ComposerType", "ComposerTypeStr", "ConsoleExporterType", "ConsoleExporterTypeStr", "ConvergenceCriterionType", "ConvergenceCriterionTypeStr", "CustomDatasetType", "CustomDatasetTypeStr", "DataExporterType", "DataExporterTypeStr", "DatasetBackingStoreType", "DatasetBackingStoreTypeStr", "DatasetClientStoreType", "DatasetClientStoreTypeStr", "DatasetFormat", "DatasetFormatStr", "DatasetSamplingStrategy", "DatasetSamplingStrategyStr", "EndpointType", "EndpointTypeStr", "GPUTelemetryCollectorType", "GPUTelemetryCollectorTypeStr", "GPUTelemetryProcessorType", "GPUTelemetryProcessorTypeStr", "PhaseType", "PhaseTypeStr", "PlotType", "PlotTypeStr", "PluginType", "PluginTypeStr", "PublicDatasetType", "PublicDatasetTypeStr", "RampType", "RampTypeStr", "RecordProcessorType", "RecordProcessorTypeStr", "ResultsProcessorType", "ResultsProcessorTypeStr", "SearchPlannerType", "SearchPlannerTypeStr", "SearchRecipePostProcessType", "SearchRecipePostProcessTypeStr", "SearchRecipeType", "SearchRecipeTypeStr", "ServerMetricsProcessorType", "ServerMetricsProcessorTypeStr", "ServiceRunType", "ServiceRunTypeStr", "ServiceType", "ServiceTypeStr", "TimingMode", "TimingModeStr", "TransportType", "TransportTypeStr", "UIType", "UITypeStr", "URLSelectionStrategy", "URLSelectionStrategyStr", "ZMQProxyType", "ZMQProxyTypeStr"]

# Plugin Protocol Categories
if TYPE_CHECKING:
    from aiperf.plugin.enums import PluginType, PluginTypeStr
else:
    _all_plugin_categories = plugins.list_categories()
    PluginType = create_enum("PluginType", {
        category.replace("-", "_").upper(): category
        for category in _all_plugin_categories
    }, module=__name__)
    PluginTypeStr: TypeAlias = str

APIRouterTypeStr: TypeAlias = str
APIRouterType = plugins.create_enum(PluginType.API_ROUTER, "APIRouterType", module=__name__)
"""Dynamic enum for api router. Example: APIRouterType.CORE, APIRouterType.PROGRESS, APIRouterType.WORKERS"""

TimingModeStr: TypeAlias = str
TimingMode = plugins.create_enum(PluginType.TIMING_STRATEGY, "TimingMode", module=__name__)
"""Dynamic enum for timing strategy. Example: TimingMode.ADAPTIVE_SCALE, TimingMode.REQUEST_RATE, TimingMode.USER_CENTRIC_RATE"""

ArrivalPatternStr: TypeAlias = str
ArrivalPattern = plugins.create_enum(PluginType.ARRIVAL_PATTERN, "ArrivalPattern", module=__name__)
"""Dynamic enum for arrival pattern. Example: ArrivalPattern.CONCURRENCY_BURST, ArrivalPattern.GAMMA, ArrivalPattern.POISSON"""

RampTypeStr: TypeAlias = str
RampType = plugins.create_enum(PluginType.RAMP, "RampType", module=__name__)
"""Dynamic enum for ramp. Example: RampType.EXPONENTIAL, RampType.LINEAR, RampType.POISSON"""

DatasetBackingStoreTypeStr: TypeAlias = str
DatasetBackingStoreType = plugins.create_enum(PluginType.DATASET_BACKING_STORE, "DatasetBackingStoreType", module=__name__)
"""Dynamic enum for dataset backing store. Example: DatasetBackingStoreType.MEMORY_MAP"""

DatasetClientStoreTypeStr: TypeAlias = str
DatasetClientStoreType = plugins.create_enum(PluginType.DATASET_CLIENT_STORE, "DatasetClientStoreType", module=__name__)
"""Dynamic enum for dataset client store. Example: DatasetClientStoreType.MEMORY_MAP"""

DatasetSamplingStrategyStr: TypeAlias = str
DatasetSamplingStrategy = plugins.create_enum(PluginType.DATASET_SAMPLER, "DatasetSamplingStrategy", module=__name__)
"""Dynamic enum for dataset sampler. Example: DatasetSamplingStrategy.RANDOM, DatasetSamplingStrategy.SEQUENTIAL, DatasetSamplingStrategy.SHUFFLE"""

ComposerTypeStr: TypeAlias = str
ComposerType = plugins.create_enum(PluginType.DATASET_COMPOSER, "ComposerType", module=__name__)
"""Dynamic enum for dataset composer. Example: ComposerType.CUSTOM, ComposerType.SYNTHETIC, ComposerType.SYNTHETIC_RANKINGS"""

CustomDatasetTypeStr: TypeAlias = str
CustomDatasetType = plugins.create_enum(PluginType.CUSTOM_DATASET_LOADER, "CustomDatasetType", module=__name__)
"""Dynamic enum for custom dataset loader. Example: CustomDatasetType.BAILIAN_TRACE, CustomDatasetType.SPEED_BENCH_THROUGHPUT_16K, CustomDatasetType.SPEED_BENCH_WRITING"""

PublicDatasetTypeStr: TypeAlias = str
PublicDatasetType = plugins.create_enum(PluginType.PUBLIC_DATASET_LOADER, "PublicDatasetType", module=__name__)
"""Dynamic enum for public dataset loader. Example: PublicDatasetType.AIMO, PublicDatasetType.MMSTAR, PublicDatasetType.VOXPOPULI"""

EndpointTypeStr: TypeAlias = str
EndpointType = plugins.create_enum(PluginType.ENDPOINT, "EndpointType", module=__name__)
"""Dynamic enum for endpoint. Example: EndpointType.CHAT, EndpointType.IMAGE_GENERATION, EndpointType.VIDEO_GENERATION"""

TransportTypeStr: TypeAlias = str
TransportType = plugins.create_enum(PluginType.TRANSPORT, "TransportType", module=__name__)
"""Dynamic enum for transport. Example: TransportType.HTTP"""

RecordProcessorTypeStr: TypeAlias = str
RecordProcessorType = plugins.create_enum(PluginType.RECORD_PROCESSOR, "RecordProcessorType", module=__name__)
"""Dynamic enum for record processor. Example: RecordProcessorType.ACCURACY_RECORD, RecordProcessorType.OUTPUTS_JSON, RecordProcessorType.RAW_RECORD_WRITER"""

ResultsProcessorTypeStr: TypeAlias = str
ResultsProcessorType = plugins.create_enum(PluginType.RESULTS_PROCESSOR, "ResultsProcessorType", module=__name__)
"""Dynamic enum for results processor. Example: ResultsProcessorType.ACCURACY_RESULTS, ResultsProcessorType.OTEL_METRICS_STREAMER, ResultsProcessorType.TIMESLICE"""

GPUTelemetryProcessorTypeStr: TypeAlias = str
GPUTelemetryProcessorType = plugins.create_enum(PluginType.GPU_TELEMETRY_PROCESSOR, "GPUTelemetryProcessorType", module=__name__)
"""Dynamic enum for gpu telemetry processor. Example: GPUTelemetryProcessorType.GPU_TELEMETRY_ACCUMULATOR, GPUTelemetryProcessorType.GPU_TELEMETRY_JSONL_WRITER"""

ServerMetricsProcessorTypeStr: TypeAlias = str
ServerMetricsProcessorType = plugins.create_enum(PluginType.SERVER_METRICS_PROCESSOR, "ServerMetricsProcessorType", module=__name__)
"""Dynamic enum for server metrics processor. Example: ServerMetricsProcessorType.SERVER_METRICS_ACCUMULATOR, ServerMetricsProcessorType.SERVER_METRICS_JSONL_WRITER"""

AccuracyGraderTypeStr: TypeAlias = str
AccuracyGraderType = plugins.create_enum(PluginType.ACCURACY_GRADER, "AccuracyGraderType", module=__name__)
"""Dynamic enum for accuracy grader. Example: AccuracyGraderType.CODE_EXECUTION, AccuracyGraderType.LIGHTEVAL_GSM8K, AccuracyGraderType.MULTIPLE_CHOICE"""

AccuracyBenchmarkTypeStr: TypeAlias = str
AccuracyBenchmarkType = plugins.create_enum(PluginType.ACCURACY_BENCHMARK, "AccuracyBenchmarkType", module=__name__)
"""Dynamic enum for accuracy benchmark. Example: AccuracyBenchmarkType.AIME, AccuracyBenchmarkType.GSM8K, AccuracyBenchmarkType.MMLU"""

DataExporterTypeStr: TypeAlias = str
DataExporterType = plugins.create_enum(PluginType.DATA_EXPORTER, "DataExporterType", module=__name__)
"""Dynamic enum for data exporter. Example: DataExporterType.ACCURACY_CSV, DataExporterType.SERVER_METRICS_CSV, DataExporterType.WANDB"""

ConsoleExporterTypeStr: TypeAlias = str
ConsoleExporterType = plugins.create_enum(PluginType.CONSOLE_EXPORTER, "ConsoleExporterType", module=__name__)
"""Dynamic enum for console exporter. Example: ConsoleExporterType.ACCURACY, ConsoleExporterType.INTERNAL_METRICS, ConsoleExporterType.USAGE_DISCREPANCY_WARNING"""

UITypeStr: TypeAlias = str
UIType = plugins.create_enum(PluginType.UI, "UIType", module=__name__)
"""Dynamic enum for ui. Example: UIType.DASHBOARD, UIType.NONE, UIType.SIMPLE"""

URLSelectionStrategyStr: TypeAlias = str
URLSelectionStrategy = plugins.create_enum(PluginType.URL_SELECTION_STRATEGY, "URLSelectionStrategy", module=__name__)
"""Dynamic enum for url selection strategy. Example: URLSelectionStrategy.ROUND_ROBIN"""

ServiceTypeStr: TypeAlias = str
ServiceType = plugins.create_enum(PluginType.SERVICE, "ServiceType", module=__name__)
"""Dynamic enum for service. Example: ServiceType.API, ServiceType.SERVER_METRICS_MANAGER, ServiceType.WORKER_MANAGER"""

ServiceRunTypeStr: TypeAlias = str
ServiceRunType = plugins.create_enum(PluginType.SERVICE_MANAGER, "ServiceRunType", module=__name__)
"""Dynamic enum for service manager. Example: ServiceRunType.MULTIPROCESSING"""

CommunicationBackendStr: TypeAlias = str
CommunicationBackend = plugins.create_enum(PluginType.COMMUNICATION, "CommunicationBackend", module=__name__)
"""Dynamic enum for communication. Example: CommunicationBackend.ZMQ_DUAL_BIND, CommunicationBackend.ZMQ_IPC, CommunicationBackend.ZMQ_TCP"""

CommClientTypeStr: TypeAlias = str
CommClientType = plugins.create_enum(PluginType.COMMUNICATION_CLIENT, "CommClientType", module=__name__)
"""Dynamic enum for communication client. Example: CommClientType.PUB, CommClientType.STREAMING_DEALER, CommClientType.SUB"""

ZMQProxyTypeStr: TypeAlias = str
ZMQProxyType = plugins.create_enum(PluginType.ZMQ_PROXY, "ZMQProxyType", module=__name__)
"""Dynamic enum for zmq proxy. Example: ZMQProxyType.DEALER_ROUTER, ZMQProxyType.PUSH_PULL, ZMQProxyType.XPUB_XSUB"""

PlotTypeStr: TypeAlias = str
PlotType = plugins.create_enum(PluginType.PLOT, "PlotType", module=__name__)
"""Dynamic enum for plot. Example: PlotType.AREA, PlotType.PERCENTILE_BANDS, PlotType.TIMESLICE"""

GPUTelemetryCollectorTypeStr: TypeAlias = str
GPUTelemetryCollectorType = plugins.create_enum(PluginType.GPU_TELEMETRY_COLLECTOR, "GPUTelemetryCollectorType", module=__name__)
"""Dynamic enum for gpu telemetry collector. Example: GPUTelemetryCollectorType.AMDSMI, GPUTelemetryCollectorType.DCGM, GPUTelemetryCollectorType.PYNVML"""

SearchRecipeTypeStr: TypeAlias = str
SearchRecipeType = plugins.create_enum(PluginType.SEARCH_RECIPE, "SearchRecipeType", module=__name__)
"""Dynamic enum for search recipe. Example: SearchRecipeType.CONCURRENCY_RAMP, SearchRecipeType.MAX_THROUGHPUT_ITL_SLA, SearchRecipeType.PREFILL_TTFT_CURVE"""

SearchRecipePostProcessTypeStr: TypeAlias = str
SearchRecipePostProcessType = plugins.create_enum(PluginType.SEARCH_RECIPE_POST_PROCESS, "SearchRecipePostProcessType", module=__name__)
"""Dynamic enum for search recipe post process. Example: SearchRecipePostProcessType.DEGRADATION_KNEE_DETECT, SearchRecipePostProcessType.PARETO_SWEEP_EXPORT, SearchRecipePostProcessType.TTFT_CURVE_FIT"""

ConvergenceCriterionTypeStr: TypeAlias = str
ConvergenceCriterionType = plugins.create_enum(PluginType.CONVERGENCE_CRITERION, "ConvergenceCriterionType", module=__name__)
"""Dynamic enum for convergence criterion. Example: ConvergenceCriterionType.CI_WIDTH, ConvergenceCriterionType.CV, ConvergenceCriterionType.DISTRIBUTION"""

SearchPlannerTypeStr: TypeAlias = str
SearchPlannerType = plugins.create_enum(PluginType.SEARCH_PLANNER, "SearchPlannerType", module=__name__)
"""Dynamic enum for search planner. Example: SearchPlannerType.BAYESIAN, SearchPlannerType.OPTUNA, SearchPlannerType.SMOOTH_ISOTONIC"""

# =============================================================================
# Composite Enums (merged from multiple categories)
# =============================================================================

PhaseTypeStr: TypeAlias = str
def _build_phasetype_members() -> dict[str, str]:
    members: dict[str, str] = {}
    for entry in plugins.list_entries(PluginType.ARRIVAL_PATTERN):
        alias = {'concurrency_burst': 'concurrency'}.get(entry.name, entry.name)
        if alias.upper() not in members:
            members[alias.upper()] = alias
    for entry in plugins.list_entries(PluginType.TIMING_STRATEGY):
        if entry.name in {'request_rate'}:
            continue
        alias = {'user_centric_rate': 'user_centric'}.get(entry.name, entry.name)
        if alias.upper() not in members:
            members[alias.upper()] = alias
    return members
PhaseType = create_enum("PhaseType", _build_phasetype_members(), module=__name__)
"""Load generation type for benchmark phases. Example: PhaseType.ADAPTIVE_SCALE, PhaseType.CONCURRENCY, PhaseType.CONSTANT"""

DatasetFormatStr: TypeAlias = str
def _build_datasetformat_members() -> dict[str, str]:
    members: dict[str, str] = {}
    for entry in plugins.list_entries(PluginType.CUSTOM_DATASET_LOADER):
        alias = {}.get(entry.name, entry.name)
        if alias.upper() not in members:
            members[alias.upper()] = alias
    return members
DatasetFormat = create_enum("DatasetFormat", _build_datasetformat_members(), module=__name__)
"""Format of file-based datasets. Mirrors the custom_dataset_loader plugin registry: every loader name surfaces here, because ``--custom-dataset-type`` resolves into ``benchmark.datasets[].file.format``. Example: DatasetFormat.BAILIAN_TRACE, DatasetFormat.BURST_GPT_TRACE, DatasetFormat.DAG_JSONL"""
